// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:news_app/api/model/source/source.dart';
import 'package:news_app/api/model/source/source_response.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SourceAdapter());
    registerAdapter(SourceResponseAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SourceAdapter());
    registerAdapter(SourceResponseAdapter());
  }
}
